name: aghari_customer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  provider: ^6.1.5
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/aghari.png
    - assets/images/welcome_icon.png
    - assets/lang/ar.json
    - assets/lang/fr.json
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/aghari.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/aghari.png"
  remove_alpha_ios: true
  min_sdk_android: 21


